<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!--
  There are several sources to find top level domain names. These ones
  are quite complete and easy to work with:

  http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
  http://publicsuffix.org/

  For new TLDs (companies, cities, international, etc.)
  http://newgtlds.icann.org/en/program-status/delegated-strings
  http://icannwiki.com/index.php/All_New_gTLD_Applications

  TLD library - - TLD declarations in XML
  Copyright (c) 2011-2021  Made to Order Software Corp.  All Rights Reserved

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
-->
<!DOCTYPE tld [
<!ELEMENT tld (area)+>
<!ELEMENT area (#PCDATA|forbid|exceptions)*>
<!ATTLIST area category (international|professionals|language|groups|region|technical|country|entrepreneurial) #REQUIRED
               country CDATA ""
               nic CDATA "">
<!ELEMENT forbid (#PCDATA)>
<!ATTLIST forbid reason (proposed|deprecated|unused|reserved|infrastructure) #REQUIRED>
<!ELEMENT exceptions (#PCDATA)>
<!ATTLIST exceptions apply-to CDATA #REQUIRED>
]>
<tld>
  <!-- international (for the whole world) -->
  <area category="international">
    .academy .active .adult .agency .airforce .allfinanz
    .analytics .apartments .app .aquarelle .arab .archi .are .army
    .art .associates .auction .audible .audio .auto .autos

    .baby .band .bank .bar .bargains .baseball .basketball .beauty .beer
    .best .bible .bid .bike .bio .biz .black .blackfriday .blog .blue
    .boats .bond .boo .book .booking .bot .boutique .box .build
    .business .buy .buzz

    .cab .cafe .call .cam .camera .camp .capital .car .cars .caravan .cards
    .care .career .careers .casa .cash .casino .catering .catholic .center
    .channel .charity .chat .cheap .christmas .church .circle .cityeats .claims
    .cleaning .click .clinic .clinique .clothing .cloud .club .coach .codes
    .coffee .college .com .community .company .computer .condos .construction
    .consulting .contact .cooking .cookingchannel .cool .coop .coupon .coupons
    .courses .credit .creditcard .creditunion .cricket .crown .cruise .cruises

    .dad .dance .data .date .dating .day .deal .deals .degree .delivery
    .democrat .design .dev .diamonds .diet .digital .direct .directory
    .discount .dish .docs .dog .domains .dot .download .drive

    .earth .eat .eco .edu .education .email .energy .engineering .enterprises
    .equipment .estate .events .exchange .exposed .express

    .fail .faith .family .fan .fans .fashion .fast .feedback .film .final
    .finance .financial .fire .fish .fishing .fit .fitness .flights .flowers
    .fly .foo .food .foodnetwork .football .forsale .forum
    .foundation .free .frogans .frontdoor .fun .fund .furniture .futbol .fyi

    .gallery .gallo .game .games .garden .gbiz .gent .gift .gifts .gives
    .glass .global .globo .gmbh .gold .golf .goo .got .graphics .gratis .green
    .gripe .grocery .group .guide .guitars .guru

    .hair .hangout .haus .health .healthcare .help .here .hermes .hiphop .hiv
    .hockey .holdings .holiday .homegoods .homes .homesense .horse .hospital
    .host .hosting .hot .hoteles .hotels .house .how

    .ice .immo .immobilien .inc .industries .info .ing .ink .institute
    .insurance .insure .investments

    .jetzt .jewelry .jobs .joy .juegos

    .kaufen .kim .kitchen .kosher

    .land .latino .law .lease .legal .lgbt .life .lifeinsurance .lifestyle
    .lighting .like .limited .limo .link .live .llc .llp .loan .loans .loft
    .lol .lotto .love .ltd .luxe .luxury

    .maison .makeup .man .management .map .market .marketing .markets .mba
    .med .media .meet .meme .memorial .men .menu .mini .mls .mobi .mobile
    .moda .moe .moi .mom .money .mormon .mortgage .moto .motorcycles .mov
    .movie .mutual

    <!-- .ngo / .ong == Non Governmental Organizations / Organizations Non Governementales -->
    .name .navy .net .network .new .news .now .ngo .ninja

    .office .one .ong .onl .online .ooo .org .organic

    .page .partners .parts .party .pet .phd .pharmacy .phone .photo
    .photography .photos .physio .pics .pictures .ping .pink .pizza .place
    .play .playstation .plus .poker .porn .press .prod .productions .promo
    .properties .property .protection .pub

    .post <!-- Also the .post is defined as "having a complex second level
            domain name rules", technically, it has no second level domain -->

    .qpon <!-- "coupon" -->

    .racing .radio .read .realestate .realtor .realty .recipes .red .rehab
    .reise .reisen .rent .rentals .repair .report .republican .rest
    .restaurant .review .reviews .rich .rip .rocks .rodeo .room .run .rsvp
    .rugby

    .safe .safety .sale .salon .sarl .save .scholarships .school .schule
    .science .search .seat .secure .security .services .sex .sexy
    .shiksha .shoes .shop .shopping .show .silk .singles .site .ski .skin
    .smile .soccer .social .software .solar .solutions .song .soy .spa .space
    .sport .spot .srl .storage .store .stream .studio .study .style .sucks
    .supplies .supply .support .surf .systems

    .talk .tattoo .tax .taxi .team .tech .technology .tel .tennis
    .theater .theatre .tickets .tienda .tips .tires .today .tools
    .top .tours .town .toys .trade .trading .training .travel
    .travelers .trust .tube .tunes

    .university .uno

    .vacations .ventures .vet .viajes .video .villas .vision .vodka
    .vote .voting .voto .voyage

    .wang .watch .watches .weather .webcam .website .wedding
    .whoswho .wiki .win .wine .work .works .wow .wtc .wtf

    .xxx .xyz

    .yachts .yoga .you

    .zip .zone

    .&#x03B5;&#x03BB; <!-- el (Greek) -->
    .&#x0431;&#x0435;&#x043B; <!-- bel (Belarussian) -->
    .&#x0434;&#x0435;&#x0442;&#x0438; <!-- kids (Russian) -->
    .&#x043C;&#x043A;&#x0434; <!-- mkd (Macedonian) -->
    .&#x043E;&#x043D;&#x043B;&#x0430;&#x0439;&#x043D; <!-- online (Russian) -->
    .&#x043E;&#x0440;&#x0433; <!-- organization (Russian) -->
    .&#x0441;&#x0430;&#x0439;&#x0442; <!-- site (Russian) -->
    .&#x0570;&#x0561;&#x0575; <!-- hye (Armenian) -->
    .&#x0628;&#x0627;&#x0632;&#x0627;&#x0631; <!-- bazaar (Arabic) -->
    .&#x0634;&#x0628;&#x0643;&#x0629; <!-- web/network (Arabic) -->
    .&#x0938;&#x0902;&#x0917;&#x0920;&#x0928; <!-- organization (Hindi) -->
    .&#x307F;&#x3093;&#x306A; <!-- everyone (Japanese) -->
    .&#x4E16;&#x754C; <!-- world (Chinese) -->
    .&#x4E2D;&#x6587;&#x7F51; <!-- chinesenetwork (Chinese) -->
    .&#x516C;&#x53F8; <!-- company (Chinese) -->
    .&#x516C;&#x76CA; <!-- charity (Chinese) -->
    .&#x5546;&#x57CE; <!-- mail (Chinese) -->
    .&#x5728;&#x7EBF; <!-- online (Chinese) -->
    .&#x6211;&#x7231;&#x4F60; <!-- I love you (Chinese) -->
    .&#x653F;&#x52A1; <!-- government (Chinese) -->
    .&#x673A;&#x6784; <!-- agencies/institutions (Chinese) -->
    .&#x6E38;&#x620F; <!-- games (Chinese) -->
    .&#x79FB;&#x52A8; <!-- mobile (Chinese) -->
    .&#x7EC4;&#x7EC7;&#x673A;&#x6784; <!-- organization (Chinese) -->
    .&#x7F51;&#x5740; <!-- network address (Chinese) -->
    .&#x7F51;&#x7EDC; <!-- network (Chinese) -->
    .&#x96C6;&#x56E2; <!-- group (Chinese) -->
    .&#x26FB3;&#x29580; <!-- Macao (Chinese, Traditional) -->
    .&#x26FB3;&#x295E8; <!-- Macao (Chinese, Simplified) -->

    <!-- yeah... .areo has gone crazy https://www.information.aero/ -->
    .aero .accident-investigation.aero .accident-prevention.aero
    .aerobatic.aero .aeroclub.aero .aerodrome.aero .agents.aero .aircraft.aero
    .airline.aero .airport.aero .air-surveillance.aero .airtraffic.aero
    .air-traffic-control.aero .ambulance.aero .amusement.aero .association.aero
    .author.aero .ballooning.aero .broker.aero .caa.aero .cargo.aero
    .catering.aero .certification.aero .championship.aero .charter.aero
    .civilaviation.aero .club.aero .conference.aero .consultant.aero
    .consulting.aero .control.aero .council.aero .crew.aero .design.aero
    .dgca.aero .educator.aero .emergency.aero .engine.aero .engineer.aero
    .entertainment.aero .equipment.aero .exchange.aero .express.aero
    .federation.aero .flight.aero .fuel.aero .gliding.aero
    .government.aero .groundhandling.aero .group.aero .hanggliding.aero
    .homebuilt.aero .insurance.aero .journal.aero .journalist.aero .leasing.aero
    .logistics.aero .magazine.aero .maintenance.aero
    .media.aero .microlight.aero .modelling.aero .navigation.aero
    .parachuting.aero .paragliding.aero .passenger-association.aero .pilot.aero
    .press.aero .production.aero .recreation.aero .repbody.aero .res.aero
    .research.aero .rotorcraft.aero .safety.aero .scientist.aero .services.aero
    .show.aero .skydiving.aero .software.aero .student.aero
    .trader.aero .trading.aero .trainer.aero .union.aero .workinggroup.aero
    .works.aero

    <!-- yeah... this is the .museum total craziness! -->
    .museum .academy.museum .agriculture.museum .air.museum .airguard.museum
    .alabama.museum .alaska.museum .amber.museum .ambulance.museum
    .american.museum .americana.museum .americanantiques.museum
    .americanart.museum .amsterdam.museum .and.museum .annefrank.museum
    .anthro.museum .anthropology.museum .antiques.museum .aquarium.museum
    .arboretum.museum .archaeological.museum .archaeology.museum
    .architecture.museum .art.museum .artanddesign.museum .artcenter.museum
    .artdeco.museum .arteducation.museum .artgallery.museum .arts.museum
    .artsandcrafts.museum .asmatart.museum .assassination.museum .assisi.museum
    .association.museum .astronomy.museum .atlanta.museum .austin.museum
    .australia.museum .automotive.museum .aviation.museum .axis.museum
    .badajoz.museum .baghdad.museum .bahn.museum .bale.museum .baltimore.museum
    .barcelona.museum .baseball.museum .basel.museum .baths.museum
    .bauern.museum .beauxarts.museum .beeldengeluid.museum .bellevue.museum
    .bergbau.museum .berkeley.museum .berlin.museum .bern.museum .bible.museum
    .bilbao.museum .bill.museum .birdart.museum .birthplace.museum .bonn.museum
    .boston.museum .botanical.museum .botanicalgarden.museum
    .botanicgarden.museum .botany.museum .brandywinevalley.museum .brasil.museum
    .bristol.museum .british.museum .britishcolumbia.museum .broadcast.museum
    .brunel.museum .brussel.museum .brussels.museum .bruxelles.museum
    .building.museum .burghof.museum .bus.museum .bushey.museum
    .cadaques.museum .california.museum .cambridge.museum .can.museum
    .canada.museum .capebreton.museum .carrier.museum .cartoonart.museum
    .casadelamoneda.museum .castle.museum .castres.museum .celtic.museum
    .center.museum .chattanooga.museum .cheltenham.museum .chesapeakebay.museum
    .chicago.museum .children.museum .childrens.museum .childrensgarden.museum
    .chiropractic.museum .chocolate.museum .christiansburg.museum
    .cincinnati.museum .cinema.museum .circus.museum .civilisation.museum
    .civilization.museum .civilwar.museum .clinton.museum .clock.museum
    .coal.museum .coastaldefence.museum .cody.museum .coldwar.museum
    .collection.museum .colonialwilliamsburg.museum .coloradoplateau.museum
    .columbia.museum .columbus.museum .communication.museum
    .communications.museum .community.museum .computer.museum
    .computerhistory.museum .comunica&#x00E7;&#x00F5;es.museum
    .contemporary.museum .contemporaryart.museum .convent.museum
    .copenhagen.museum .corporation.museum
    .correios-e-telecomunica&#x00E7;&#x00F5;es.museum
    .corvette.museum .costume.museum .countryestate.museum .county.museum
    .crafts.museum .cranbrook.museum .creation.museum .cultural.museum
    .culturalcenter.museum .culture.museum .cyber.museum .cymru.museum
    .dali.museum .dallas.museum .database.museum .ddr.museum
    .decorativearts.museum .delaware.museum .delmenhorst.museum .denmark.museum
    .depot.museum .design.museum .detroit.museum .dinosaur.museum
    .discovery.museum .dolls.museum .donostia.museum .durham.museum
    .eastafrica.museum .eastcoast.museum .education.museum .educational.museum
    .egyptian.museum .eisenbahn.museum .elburg.museum .elvendrell.museum
    .embroidery.museum .encyclopedic.museum .england.museum .entomology.museum
    .environment.museum .environmentalconservation.museum .epilepsy.museum
    .essex.museum .estate.museum .ethnology.museum .exeter.museum
    .exhibition.museum .family.museum .farm.museum .farmequipment.museum
    .farmers.museum .farmstead.museum .field.museum .figueres.museum
    .filatelia.museum .film.museum .fineart.museum .finearts.museum
    .finland.museum .flanders.museum .florida.museum .force.museum
    .fortmissoula.museum .fortworth.museum .foundation.museum .francaise.museum
    .frankfurt.museum .franziskaner.museum .freemasonry.museum .freiburg.museum
    .fribourg.museum .frog.museum .fundacio.museum .furniture.museum
    .gallery.museum .garden.museum .gateway.museum .geelvinck.museum
    .gemological.museum .geology.museum .georgia.museum .giessen.museum
    .glas.museum .glass.museum .gorge.museum .grandrapids.museum .graz.museum
    .guernsey.museum .halloffame.museum .hamburg.museum .handson.museum
    .harvestcelebration.museum .hawaii.museum .health.museum
    .heimatunduhren.museum .hellas.museum .helsinki.museum
    .hembygdsforbund.museum .heritage.museum .histoire.museum .historical.museum
    .historicalsociety.museum .historichouses.museum .historisch.museum
    .historisches.museum .history.museum .historyofscience.museum
    .horology.museum .house.museum .humanities.museum .illustration.museum
    .imageandsound.museum .indian.museum .indiana.museum
    .indianapolis.museum .indianmarket.museum .intelligence.museum
    .interactive.museum .iraq.museum .iron.museum
    .isleofman.museum .jamison.museum .jefferson.museum
    .jerusalem.museum .jewelry.museum .jewish.museum
    .jewishart.museum .jfk.museum .journalism.museum
    .judaica.museum .judygarland.museum .juedisches.museum
    .juif.museum .karate.museum .karikatur.museum
    .kids.museum .koebenhavn.museum .koeln.museum
    .kunst.museum .kunstsammlung.museum .kunstunddesign.museum
    .labor.museum .labour.museum .lajolla.museum
    .lancashire.museum .landes.museum .lans.museum .l&#x00E4;ns.museum
    .larsson.museum .lewismiller.museum .lincoln.museum .linz.museum
    .living.museum .livinghistory.museum .localhistory.museum .london.museum
    .losangeles.museum .louvre.museum .loyalist.museum .lucerne.museum
    .luxembourg.museum .luzern.museum .mad.museum .madrid.museum
    .mallorca.museum .manchester.museum .mansion.museum .mansions.museum
    .manx.museum .marburg.museum .maritime.museum .maritimo.museum
    .maryland.museum .marylhurst.museum .media.museum .medical.museum
    .medizinhistorisches.museum .meeres.museum .memorial.museum
    .mesaverde.museum .michigan.museum .midatlantic.museum .military.museum
    .mill.museum .miners.museum .mining.museum .minnesota.museum
    .missile.museum .missoula.museum .modern.museum .moma.museum
    .money.museum .monmouth.museum .monticello.museum .montreal.museum
    .moscow.museum .motorcycle.museum .muenchen.museum .muenster.museum
    .mulhouse.museum .muncie.museum .museet.museum .museumcenter.museum
    .museumvereniging.museum .music.museum .national.museum
    .nationalfirearms.museum .nationalheritage.museum .nativeamerican.museum
    .naturalhistory.museum .naturalhistorymuseum.museum .naturalsciences.museum
    .nature.museum .naturhistorisches.museum .natuurwetenschappen.museum
    .naumburg.museum .naval.museum .nebraska.museum
    .neues.museum .newhampshire.museum .newjersey.museum
    .newmexico.museum .newport.museum .newspaper.museum
    .newyork.museum .niepce.museum .norfolk.museum
    .north.museum .nrw.museum
    .nyc.museum .nyny.museum
    .oceanographic.museum .oceanographique.museum .omaha.museum
    .online.museum .ontario.museum .openair.museum
    .oregon.museum .oregontrail.museum .otago.museum
    .oxford.museum .pacific.museum .paderborn.museum
    .palace.museum .paleo.museum .palmsprings.museum
    .panama.museum .paris.museum .pasadena.museum
    .pharmacy.museum .philadelphia.museum .philadelphiaarea.museum
    .philately.museum .phoenix.museum .photography.museum
    .pilots.museum .pittsburgh.museum .planetarium.museum
    .plantation.museum .plants.museum .plaza.museum
    .portal.museum .portland.museum .portlligat.museum
    .posts-and-telecommunications.museum .preservation.museum .presidio.museum
    .press.museum .project.museum .public.museum
    .pubol.museum .quebec.museum .railroad.museum
    .railway.museum .research.museum .resistance.museum .riodejaneiro.museum
    .rochester.museum .rockart.museum .roma.museum .russia.museum
    .saintlouis.museum .salem.museum .salvadordali.museum .salzburg.museum
    .sandiego.museum .sanfrancisco.museum .santabarbara.museum .santacruz.museum
    .santafe.museum .saskatchewan.museum .satx.museum .savannahga.museum
    .schlesisches.museum .schoenbrunn.museum .schokoladen.museum .school.museum
    .schweiz.museum .science.museum .scienceandhistory.museum
    .scienceandindustry.museum .sciencecenter.museum .sciencecenters.museum
    .science-fiction.museum .sciencehistory.museum .sciences.museum
    .sciencesnaturelles.museum .scotland.museum .seaport.museum
    .settlement.museum .settlers.museum .shell.museum .sherbrooke.museum
    .sibenik.museum .silk.museum .ski.museum .skole.museum .society.museum
    .sologne.museum .soundandvision.museum .southcarolina.museum
    .southwest.museum .space.museum .spy.museum .square.museum .stadt.museum
    .stalbans.museum .starnberg.museum .state.museum .stateofdelaware.museum
    .station.museum .steam.museum .steiermark.museum .stjohn.museum
    .stockholm.museum .stpetersburg.museum .stuttgart.museum .suisse.museum
    .surgeonshall.museum .surrey.museum .svizzera.museum .sweden.museum
    .sydney.museum .tank.museum .tcm.museum .technology.museum
    .telekommunikation.museum .television.museum .texas.museum .textile.museum
    .theater.museum .time.museum .timekeeping.museum .topology.museum
    .torino.museum .touch.museum .town.museum .transport.museum
    .tree.museum .trolley.museum .trust.museum .trustee.museum
    .uhren.museum .ulm.museum .undersea.museum .university.museum
    .usa.museum .usantiques.museum .usarts.museum .uscountryestate.museum
    .usculture.museum .usdecorativearts.museum .usgarden.museum
    .ushistory.museum .ushuaia.museum .uslivinghistory.museum .utah.museum
    .uvic.museum .valley.museum .vantaa.museum .versailles.museum
    .viking.museum .village.museum .virginia.museum .virtual.museum
    .virtuel.museum .vlaanderen.museum .volkenkunde.museum .wales.museum
    .wallonie.museum .war.museum .washingtondc.museum .watchandclock.museum
    .watch-and-clock.museum .western.museum .westfalen.museum .whaling.museum
    .wildlife.museum .williamsburg.museum .windmill.museum .workshop.museum
    .york.museum .yorkshire.museum .yosemite.museum .youth.museum
    .zoological.museum .zoology.museum
    .&#x05D9;&#x05E8;&#x05D5;&#x05E9;&#x05DC;&#x05D9;&#x05DD;.museum
    .&#x0438;&#x043A;&#x043E;&#x043C;.museum

    <forbid reason="deprecated">.africamagic .boots .freight.aero
    .marketplace.aero .mutuelle .nato .nuernberg.museum .nuremberg.museum
    .taxi.aero .wed</forbid>
    <forbid reason="proposed">.mail .web</forbid>
    <!-- example.com and example.net are domain names, not just TLDs -->
    <!--forbid reason="example">.example.com .example.net</forbid-->
  </area>

  <!-- specialized TLDs -->
  <area category="brand">
    .aaa .aarp .abarth .abb .abbott .abbvie .abc .able .abogado .abudhabi
    .accenture .aco .adac .ads .aeg .aetna .afamilycompany
    .afl .agakhan .aig .airbus .airtel .akdn .alfaromeo .alibaba
    .alipay .allstate .ally .alstom .amazon .americanexpress .americanfamily
    .amex .amfam .amica .android .anquan .anz .aol .apple .aramco .arte
    .asda .astrium .athleta .audi .auspost .avianca .aws
    .axa .azure

    .baidu .banamex .bananarepublic .barclaycard .barclays
    .barefoot .bauhaus .bbc .bbt .bbva .bcg .bcn .beats .bentley .bestbuy
    .bet .bharti .bing .bingo .blockbuster .bloomberg .bms .bmw
    .bnpparibas .boehringer .bofa .bom .bosch .bostik .bradesco .bridgestone
    .brother .bugatti

    .cal .calvinklein .canon .capitalone .case
    .cba .cbn .cbre .cbs .cern .cfa .cfd .chanel .chase .chintai
    .chrome .cipriani .cisco .citadel .citi .citic .clubmed
    .comcast .commbank .compare .comsec .cpa .crs .csc .cuisinella .cyou

    .dabur .datsun .dclk .dds .dell .deloitte .delta .desi .dhl .discover .diy
    .dnp .dtv .duck .dunlop .dupont .durban .dvag .dvr

    .edeka .emerck .epson .ericsson .erni .etisalat
    .eurovision .extraspace

    .fage .fairwinds .farmers .fedex .ferrari .ferrero
    .fiat .fidelity .fido .firestone .firmdale .flickr .flir .ford .forex
    .fox .fresenius .frl .frontier .ftr .fujitsu

    .gallup .gap .gdn .gea .genting .george .ggee .giving .glade .godaddy
    .goodyear .gle .gmail .gmo .gmx .goldpoint .goog
    .google .gop .grainger .guardian .gucci .guge

    .hbo .hdfc .hdfcbank .hgtv .hisamitsu .hitachi .hkt .homedepot .honda
    .hotmail .hsbc .hughes .hyatt .hyundai

    .ibm .icbc .icu .ieee .ifm .ikano .imamat .imdb .infiniti
    .intuit .ipiranga .ismaili .ist .itau .itv

    .jaguar .java .jcb .jeep .jio .jll .jmp .jnj .jot .jpmorgan
    .jprs .juniper

    .kddi .kerryhotels .kerrylogistics .kerryproperties .kfh .kia .kinder
    .kindle .komatsu .kpmg .kpn .kred .kuokgroup .kyoto

    .lacaixa .lamborghini .lamer .lancaster .lancia
    .landrover .lanxess .lasalle .latrobe .lefrak .lego .lexus
    .lidl .lilly .lincoln .linde .lipsy .living .lixil .locker .locus
    .lotte .lpl .lplfinancial .ltda .lundbeck

    .macys .maif .mango .marriott .marshalls .maserati .mattel
    .mckinsey .merckmsd .microsoft .mint .mit .mitsubishi
    .mlb .mma .mnet .monash .monster .msd
    .mtn .mtr

    .nab .natura .nba .nec .netbank .netflix .neustar
    .next .nextdirect .nexus .nfl .nhk .nico .nike .nikon
    .nissan .nissay .nokia .northwesternmutual .norton .nowruz .nowtv .nra .ntt

    .obi .observer .off .olayan .olayangroup .oldnavy .ollo .omega
    .open .oracle .orange .origins .osaka
    .otsuka .ott .ovh

    .panasonic .pars .passagens .pay .pccw
    .pfizer .philips .pictet .pid .pin .pioneer .pnc .pohl
    .politie .pramerica .praxi .prime .progressive .pru .prudential
    .pwc

    .quest .qvc

    .raid .redstone .redumbrella .ren .reit .reliance .rexroth .richardli
    .ricoh .ril .rmit .rocher .rogers .rwe

    .sakura .samsclub .samsung .sandvik .sandvikcoromant .sanofi .sap
    .sas .saxo .sbi .sbs .sca .scb .schaeffler .schmidt .schwarz .scjohnson
    .seek .select .sener .ses .seven .sew .sfr .shangrila .sharp .shaw
    .shell .shia .shouji .showtime .sina .sky .skype .sling .smart
    .sncf .softbank .sohu .sony .stada .staples
    .star .statebank .statefarm .stc .stcgroup .suzuki
    .swatch .swiftcover .swiss .sydney

    .tab .taipei .taobao .target .tatamotors .tatar .tci .tdk
    .teva .temasek .thd .tiaa .tiffany .tjmaxx .tjx
    .tkmaxx .tmall .toray .toshiba .total .toyota .travelchannel
    .travelersinsurance .trv .tui .tushu .tvs

    .ubank .ubs .unicom .uol .ups

    .vana .vanguard .verisign .verm&#x00F6;gensberater
    .verm&#x00F6;gensberatung .versicherung .vig .viking .vin .vip .virgin
    .visa .viva .vivo .vlaanderen .volkswagen .volvo
    .vuelos

    .walmart .walter .wanggou .weatherchannel .weber .weibo .weir
    .williamhill .winners .windows .wme .wolterskluwer .woodside

    .xbox .xerox .xfinity .xihuan .xin

    .yahoo .yamaxun .yandex .yodobashi .youtube .yun

    .zappos .zara .zero

    .&#x0440;&#x0443;&#x0441; <!-- Rusnames Limited -->
    .&#x0431;&#x0438;&#x0437;.&#x0440;&#x0443;&#x0441;
    .&#x043A;&#x043E;&#x043C;.&#x0440;&#x0443;&#x0441;
    .&#x043A;&#x0440;&#x044B;&#x043C;.&#x0440;&#x0443;&#x0441;
    .&#x043C;&#x0438;&#x0440;.&#x0440;&#x0443;&#x0441;
    .&#x043C;&#x0441;&#x043A;.&#x0440;&#x0443;&#x0441;
    .&#x043E;&#x0440;&#x0433;.&#x0440;&#x0443;&#x0441;
    .&#x0441;&#x0430;&#x043C;&#x0430;&#x0440;&#x0430;.&#x0440;&#x0443;&#x0441;
    .&#x0441;&#x043E;&#x0447;&#x0438;.&#x0440;&#x0443;&#x0441;
    .&#x0441;&#x043F;&#x0431;.&#x0440;&#x0443;&#x0441;
    .&#x044F;.&#x0440;&#x0443;&#x0441;

    .&#x043A;&#x0430;&#x0442;&#x043E;&#x043B;&#x0438;&#x043A; <!-- Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication) -->
    .&#x043A;&#x043E;&#x043C; <!-- VeriSign Sarl -->
    .&#x05E7;&#x05D5;&#x05DD; <!-- VeriSign Sarl -->
    .&#x0627;&#x0628;&#x0648;&#x0638;&#x0628;&#x064A; <!-- Abu Dhabi Systems and Information Centre -->
    .&#x0627;&#x062A;&#x0635;&#x0627;&#x0644;&#x0627;&#x062A; <!-- Emirates Telecommunications Corporation (trading as Etisalat) -->
    .&#x0627;&#x0631;&#x0627;&#x0645;&#x0643;&#x0648; <!-- Aramco Services Company -->
    .&#x0627;&#x0644;&#x0639;&#x0644;&#x064A;&#x0627;&#x0646; <!-- Crescent Holding GmbH -->
    .&#x0628;&#x064A;&#x062A;&#x0643; <!-- Kuwait Finance House -->
    .&#x0639;&#x0631;&#x0628; <!-- League of Arab States -->
    .&#x0643;&#x0627;&#x062B;&#x0648;&#x0644;&#x064A;&#x0643; <!-- Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication) -->
    .&#x0643;&#x0648;&#x0645; <!-- VeriSign Sarl -->
    .&#x0645;&#x0648;&#x0628;&#x0627;&#x064A;&#x0644;&#x064A; <!-- GreenTech Consultancy Company W.L.L. -->
    .&#x0645;&#x0648;&#x0642;&#x0639; <!-- Suhub Electronic Establishment -->
    .&#x0647;&#x0645;&#x0631;&#x0627;&#x0647; <!-- Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti. -->
    .&#x0928;&#x0947;&#x091F; <!-- VeriSign Sarl -->
    .&#x30B0;&#x30FC;&#x30B0;&#x30EB; <!-- Charleston Road Registry Inc. -->
    .&#x4E00;&#x53F7;&#x5E97; <!-- Wal-Mart Stores, Inc. -->
    .&#x4E2D;&#x4FE1; <!-- Citic (Chinese) -->
    .&#x4F01;&#x4E1A; <!-- Dash McCook, LLC -->
    .&#x4F5B;&#x5C71; <!-- Guangzhou YU Wei Information Technology Co., Ltd. -->
    .&#x516B;&#x5366; <!-- Zodiac Scorpio Limited -->
    .&#x5546;&#x5E97; <!-- Wild Island, LLC -->
    .&#x5546;&#x6807; <!-- Dot Trademark TLD Holding Company Limted (was: HU YI GLOBAL INFORMATION RESOURCES (HOLDING) COMPANY.HONGKONG LIMITED) -->
    .&#x5609;&#x91CC; <!-- Kerry Trading Co. Limited -->
    .&#x5929;&#x4E3B;&#x6559; <!-- Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication) -->
    .&#x5A31;&#x4E50; <!-- Will Bloom, LLC -->
    .&#x5E7F;&#x4E1C; <!-- Guangzhou YU Wei Information Technology Co., Ltd. -->
    .&#x6148;&#x5584; <!-- Excellent First Limited -->
    .&#x624B;&#x673A; <!-- Beijing RITT-Net Technology Development Co., Ltd -->
    .&#x62DB;&#x8058; <!-- Dot Trademark TLD Holding Company Limited -->
    .&#x653F;&#x5E9C; <!-- Net-Chinese Co., Ltd. -->
    .&#x65B0;&#x95FB; <!-- Xinhua News Agency Guangdong Branch -->
    .&#x65F6;&#x5C1A; <!-- RISE VICTORY LIMITED -->
    .&#x6DE1;&#x9A6C;&#x9521; <!-- Temasek Holdings (Private) Limited -->
    .&#x7F51;&#x5E97; <!-- Zodiac Libra Limited -->
    .&#x8C37;&#x6B4C; <!-- Charleston Road Registry Inc. -->
    .&#x901A;&#x8CA9; <!-- Amazon EU S.à r.l. -->
    .&#x96FB;&#x8A0A;&#x76C8;&#x79D1; <!-- PCCW Enterprises Limited -->
    .&#x9999;&#x683C;&#x91CC;&#x62C9; <!-- Shangri¿La International Hotel Management Limited -->
    .&#xC0BC;&#xC131; <!-- Samsung (Korean) -->
    .&#x20915;&#x20949;&#x2092E; <!-- VeriSign Sarl -->
    .&#x20928;&#x2091F; <!-- VeriSign Sarl -->
    .&#x20E04;&#x20E2D;&#x20E21; <!-- VeriSign Sarl -->
    .&#x230AF;&#x230E9;&#x230A6;&#x230C9; <!-- Amazon EU S.a.r.l. -->
    .&#x230B3;&#x230E0; <!-- VeriSign Sarl -->
    .&#x230B9;&#x230C8;&#x230A2; <!-- Amazon EU S.a.r.l -->
    .&#x230BB;&#x230FC;&#x230EB; <!-- Amazon EU S.a.r.l -->
    .&#x230DD;&#x230A4;&#x230F3;&#x230C8; <!-- Amazon EU S.a.r.l -->
    .&#x230D5;&#x230A1;&#x230C3;&#x230B7;&#x230E7;&#x230F3; <!-- Amazon EU S.a.r.l -->
    .&#x24FE1;&#x2606F; <!-- Beijing Tele-info Network Technology Co., Ltd. -->
    .&#x25065;&#x25EB7; <!-- Stable Tone Limited -->
    .&#x25609;&#x291CC;&#x25927;&#x29152;&#x25E97; <!-- Kerry Trading Co. Limited -->
    .&#x25927;&#x24F17;&#x26C7D;&#x28F66; <!-- Volkswagen (China) Investment Co., Ltd. -->
    .&#x25927;&#x262FF; <!-- VeriSign Sarl -->
    .&#x25BB6;&#x296FB; <!-- Amazon EU S.a.r.l -->
    .&#x25DE5;&#x2884C; <!-- Industrial and Commercial Bank of China Limited -->
    .&#x25FAE;&#x2535A; <!-- China Uniter Network Communications Corporation Limited -->
    .&#x2624B;&#x28868; <!-- Richemont DNS Inc. -->
    .&#x266F8;&#x27C4D; <!-- Amazon EU S.a.r.l -->
    .&#x270B9;&#x2770B; <!-- VeriSign Sarl -->
    .&#x273E0;&#x25B9D; <!-- Richemont DNS Inc. -->
    .&#x27F51;&#x27AD9; <!-- Global Website TLD Asia Limited -->
    .&#x28054;&#x2901A; <!-- China Uniter Network Communications Corporation Limited -->
    .&#x28BFA;&#x257FA;&#x24E9A; <!-- Nokia Corporation -->
    .&#x28D2D;&#x27269; <!-- Minds + Machines Group Limited -->
    .&#x296FB;&#x28A0A;&#x278C8;&#x279D1; <!-- PCCW Enterprises Limited -->
    .&#x298DE;&#x25229;&#x26D66; <!-- Koninklijke Philips N.V. -->
    .&#x298DF;&#x254C1; <!-- Amazon EU S.a.r.l -->